apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mandala-worker-scaledobject
spec:
  scaleTargetRef:
    name: mandala-worker
  pollingInterval: 30
  cooldownPeriod: 300
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: nats-jetstream
    metadata:
      natsServerMonitoringEndpoint: "http://nats.monitoring:8222"
      streamName: tasks
      consumerName: worker
      pendingMessages: "100"

