// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/proto/meta.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetaScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaScoreRequest) Reset() {
	*x = MetaScoreRequest{}
	mi := &file_api_proto_meta_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaScoreRequest) ProtoMessage() {}

func (x *MetaScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_meta_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaScoreRequest.ProtoReflect.Descriptor instead.
func (*MetaScoreRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_meta_proto_rawDescGZIP(), []int{0}
}

type MetaScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	CombinedScore float64                `protobuf:"fixed64,2,opt,name=combined_score,json=combinedScore,proto3" json:"combined_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaScore) Reset() {
	*x = MetaScore{}
	mi := &file_api_proto_meta_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaScore) ProtoMessage() {}

func (x *MetaScore) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_meta_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaScore.ProtoReflect.Descriptor instead.
func (*MetaScore) Descriptor() ([]byte, []int) {
	return file_api_proto_meta_proto_rawDescGZIP(), []int{1}
}

func (x *MetaScore) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *MetaScore) GetCombinedScore() float64 {
	if x != nil {
		return x.CombinedScore
	}
	return 0
}

type MetaScoreList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*MetaScore           `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaScoreList) Reset() {
	*x = MetaScoreList{}
	mi := &file_api_proto_meta_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaScoreList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaScoreList) ProtoMessage() {}

func (x *MetaScoreList) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_meta_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaScoreList.ProtoReflect.Descriptor instead.
func (*MetaScoreList) Descriptor() ([]byte, []int) {
	return file_api_proto_meta_proto_rawDescGZIP(), []int{2}
}

func (x *MetaScoreList) GetScores() []*MetaScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_api_proto_meta_proto protoreflect.FileDescriptor

const file_api_proto_meta_proto_rawDesc = "" +
	"\n" +
	"\x14api/proto/meta.proto\x12\x05proto\"\x12\n" +
	"\x10MetaScoreRequest\"M\n" +
	"\tMetaScore\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12%\n" +
	"\x0ecombined_score\x18\x02 \x01(\x01R\rcombinedScore\"9\n" +
	"\rMetaScoreList\x12(\n" +
	"\x06scores\x18\x01 \x03(\v2\x10.proto.MetaScoreR\x06scores2S\n" +
	"\x10MetaScoreService\x12?\n" +
	"\x0eListMetaScores\x12\x17.proto.MetaScoreRequest\x1a\x14.proto.MetaScoreListB:Z8github.com/GenesisAeon/unifiedmandala-go/api/proto;protob\x06proto3"

var (
	file_api_proto_meta_proto_rawDescOnce sync.Once
	file_api_proto_meta_proto_rawDescData []byte
)

func file_api_proto_meta_proto_rawDescGZIP() []byte {
	file_api_proto_meta_proto_rawDescOnce.Do(func() {
		file_api_proto_meta_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_meta_proto_rawDesc), len(file_api_proto_meta_proto_rawDesc)))
	})
	return file_api_proto_meta_proto_rawDescData
}

var file_api_proto_meta_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_meta_proto_goTypes = []any{
	(*MetaScoreRequest)(nil), // 0: proto.MetaScoreRequest
	(*MetaScore)(nil),        // 1: proto.MetaScore
	(*MetaScoreList)(nil),    // 2: proto.MetaScoreList
}
var file_api_proto_meta_proto_depIdxs = []int32{
	1, // 0: proto.MetaScoreList.scores:type_name -> proto.MetaScore
	0, // 1: proto.MetaScoreService.ListMetaScores:input_type -> proto.MetaScoreRequest
	2, // 2: proto.MetaScoreService.ListMetaScores:output_type -> proto.MetaScoreList
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_meta_proto_init() }
func file_api_proto_meta_proto_init() {
	if File_api_proto_meta_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_meta_proto_rawDesc), len(file_api_proto_meta_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_meta_proto_goTypes,
		DependencyIndexes: file_api_proto_meta_proto_depIdxs,
		MessageInfos:      file_api_proto_meta_proto_msgTypes,
	}.Build()
	File_api_proto_meta_proto = out.File
	file_api_proto_meta_proto_goTypes = nil
	file_api_proto_meta_proto_depIdxs = nil
}
