// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/proto/meta.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetaScoreService_ListMetaScores_FullMethodName = "/proto.MetaScoreService/ListMetaScores"
)

// MetaScoreServiceClient is the client API for MetaScoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MetaScoreServiceClient interface {
	ListMetaScores(ctx context.Context, in *MetaScoreRequest, opts ...grpc.CallOption) (*MetaScoreList, error)
}

type metaScoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetaScoreServiceClient(cc grpc.ClientConnInterface) MetaScoreServiceClient {
	return &metaScoreServiceClient{cc}
}

func (c *metaScoreServiceClient) ListMetaScores(ctx context.Context, in *MetaScoreRequest, opts ...grpc.CallOption) (*MetaScoreList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetaScoreList)
	err := c.cc.Invoke(ctx, MetaScoreService_ListMetaScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetaScoreServiceServer is the server API for MetaScoreService service.
// All implementations must embed UnimplementedMetaScoreServiceServer
// for forward compatibility.
type MetaScoreServiceServer interface {
	ListMetaScores(context.Context, *MetaScoreRequest) (*MetaScoreList, error)
	mustEmbedUnimplementedMetaScoreServiceServer()
}

// UnimplementedMetaScoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetaScoreServiceServer struct{}

func (UnimplementedMetaScoreServiceServer) ListMetaScores(context.Context, *MetaScoreRequest) (*MetaScoreList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMetaScores not implemented")
}
func (UnimplementedMetaScoreServiceServer) mustEmbedUnimplementedMetaScoreServiceServer() {}
func (UnimplementedMetaScoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeMetaScoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetaScoreServiceServer will
// result in compilation errors.
type UnsafeMetaScoreServiceServer interface {
	mustEmbedUnimplementedMetaScoreServiceServer()
}

func RegisterMetaScoreServiceServer(s grpc.ServiceRegistrar, srv MetaScoreServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetaScoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetaScoreService_ServiceDesc, srv)
}

func _MetaScoreService_ListMetaScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetaScoreServiceServer).ListMetaScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetaScoreService_ListMetaScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetaScoreServiceServer).ListMetaScores(ctx, req.(*MetaScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetaScoreService_ServiceDesc is the grpc.ServiceDesc for MetaScoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetaScoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MetaScoreService",
	HandlerType: (*MetaScoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListMetaScores",
			Handler:    _MetaScoreService_ListMetaScores_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/meta.proto",
}
