// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: simulations/universe-sim/api/sim.proto

package sim

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float64                `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Vector) Reset() {
	*x = Vector{}
	mi := &file_simulations_universe_sim_api_sim_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vector) ProtoMessage() {}

func (x *Vector) ProtoReflect() protoreflect.Message {
	mi := &file_simulations_universe_sim_api_sim_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vector.ProtoReflect.Descriptor instead.
func (*Vector) Descriptor() ([]byte, []int) {
	return file_simulations_universe_sim_api_sim_proto_rawDescGZIP(), []int{0}
}

func (x *Vector) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Vector) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      *Vector                `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Velocity      *Vector                `protobuf:"bytes,2,opt,name=velocity,proto3" json:"velocity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_simulations_universe_sim_api_sim_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_simulations_universe_sim_api_sim_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_simulations_universe_sim_api_sim_proto_rawDescGZIP(), []int{1}
}

func (x *Entity) GetPosition() *Vector {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Entity) GetVelocity() *Vector {
	if x != nil {
		return x.Velocity
	}
	return nil
}

type State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*Entity              `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *State) Reset() {
	*x = State{}
	mi := &file_simulations_universe_sim_api_sim_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*State) ProtoMessage() {}

func (x *State) ProtoReflect() protoreflect.Message {
	mi := &file_simulations_universe_sim_api_sim_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use State.ProtoReflect.Descriptor instead.
func (*State) Descriptor() ([]byte, []int) {
	return file_simulations_universe_sim_api_sim_proto_rawDescGZIP(), []int{2}
}

func (x *State) GetEntities() []*Entity {
	if x != nil {
		return x.Entities
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_simulations_universe_sim_api_sim_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_simulations_universe_sim_api_sim_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_simulations_universe_sim_api_sim_proto_rawDescGZIP(), []int{3}
}

var File_simulations_universe_sim_api_sim_proto protoreflect.FileDescriptor

const file_simulations_universe_sim_api_sim_proto_rawDesc = "" +
	"\n" +
	"&simulations/universe-sim/api/sim.proto\x12\x03sim\"$\n" +
	"\x06Vector\x12\f\n" +
	"\x01x\x18\x01 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x01R\x01y\"Z\n" +
	"\x06Entity\x12'\n" +
	"\bposition\x18\x01 \x01(\v2\v.sim.VectorR\bposition\x12'\n" +
	"\bvelocity\x18\x02 \x01(\v2\v.sim.VectorR\bvelocity\"0\n" +
	"\x05State\x12'\n" +
	"\bentities\x18\x01 \x03(\v2\v.sim.EntityR\bentities\"\a\n" +
	"\x05Empty21\n" +
	"\vUniverseSim\x12\"\n" +
	"\bGetState\x12\n" +
	".sim.Empty\x1a\n" +
	".sim.StateBIZGgithub.com/GenesisAeon/unified-mandala/simulations/universe-sim/api;simb\x06proto3"

var (
	file_simulations_universe_sim_api_sim_proto_rawDescOnce sync.Once
	file_simulations_universe_sim_api_sim_proto_rawDescData []byte
)

func file_simulations_universe_sim_api_sim_proto_rawDescGZIP() []byte {
	file_simulations_universe_sim_api_sim_proto_rawDescOnce.Do(func() {
		file_simulations_universe_sim_api_sim_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_simulations_universe_sim_api_sim_proto_rawDesc), len(file_simulations_universe_sim_api_sim_proto_rawDesc)))
	})
	return file_simulations_universe_sim_api_sim_proto_rawDescData
}

var file_simulations_universe_sim_api_sim_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_simulations_universe_sim_api_sim_proto_goTypes = []any{
	(*Vector)(nil), // 0: sim.Vector
	(*Entity)(nil), // 1: sim.Entity
	(*State)(nil),  // 2: sim.State
	(*Empty)(nil),  // 3: sim.Empty
}
var file_simulations_universe_sim_api_sim_proto_depIdxs = []int32{
	0, // 0: sim.Entity.position:type_name -> sim.Vector
	0, // 1: sim.Entity.velocity:type_name -> sim.Vector
	1, // 2: sim.State.entities:type_name -> sim.Entity
	3, // 3: sim.UniverseSim.GetState:input_type -> sim.Empty
	2, // 4: sim.UniverseSim.GetState:output_type -> sim.State
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_simulations_universe_sim_api_sim_proto_init() }
func file_simulations_universe_sim_api_sim_proto_init() {
	if File_simulations_universe_sim_api_sim_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_simulations_universe_sim_api_sim_proto_rawDesc), len(file_simulations_universe_sim_api_sim_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simulations_universe_sim_api_sim_proto_goTypes,
		DependencyIndexes: file_simulations_universe_sim_api_sim_proto_depIdxs,
		MessageInfos:      file_simulations_universe_sim_api_sim_proto_msgTypes,
	}.Build()
	File_simulations_universe_sim_api_sim_proto = out.File
	file_simulations_universe_sim_api_sim_proto_goTypes = nil
	file_simulations_universe_sim_api_sim_proto_depIdxs = nil
}
