// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: simulations/universe-sim/api/sim.proto

package sim

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UniverseSim_GetState_FullMethodName = "/sim.UniverseSim/GetState"
)

// UniverseSimClient is the client API for UniverseSim service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UniverseSimClient interface {
	GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*State, error)
}

type universeSimClient struct {
	cc grpc.ClientConnInterface
}

func NewUniverseSimClient(cc grpc.ClientConnInterface) UniverseSimClient {
	return &universeSimClient{cc}
}

func (c *universeSimClient) GetState(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*State, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(State)
	err := c.cc.Invoke(ctx, UniverseSim_GetState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UniverseSimServer is the server API for UniverseSim service.
// All implementations must embed UnimplementedUniverseSimServer
// for forward compatibility.
type UniverseSimServer interface {
	GetState(context.Context, *Empty) (*State, error)
	mustEmbedUnimplementedUniverseSimServer()
}

// UnimplementedUniverseSimServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUniverseSimServer struct{}

func (UnimplementedUniverseSimServer) GetState(context.Context, *Empty) (*State, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetState not implemented")
}
func (UnimplementedUniverseSimServer) mustEmbedUnimplementedUniverseSimServer() {}
func (UnimplementedUniverseSimServer) testEmbeddedByValue()                     {}

// UnsafeUniverseSimServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UniverseSimServer will
// result in compilation errors.
type UnsafeUniverseSimServer interface {
	mustEmbedUnimplementedUniverseSimServer()
}

func RegisterUniverseSimServer(s grpc.ServiceRegistrar, srv UniverseSimServer) {
	// If the following call pancis, it indicates UnimplementedUniverseSimServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UniverseSim_ServiceDesc, srv)
}

func _UniverseSim_GetState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniverseSimServer).GetState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniverseSim_GetState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniverseSimServer).GetState(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// UniverseSim_ServiceDesc is the grpc.ServiceDesc for UniverseSim service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UniverseSim_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sim.UniverseSim",
	HandlerType: (*UniverseSimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetState",
			Handler:    _UniverseSim_GetState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simulations/universe-sim/api/sim.proto",
}
