from typing import Any, Mapping

class DataArray:
    size: int
    values: Any
    def to_array(self) -> "DataArray": ...
    def isnull(self) -> "DataArray": ...
    def sum(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_numpy(self) -> Any: ...
    def astype(self, *args: Any, **kwargs: Any) -> Any: ...

class Dataset:
    data_vars: Mapping[str, DataArray]
    coords: Mapping[str, Any]
    indexes: Mapping[str, Any]
    def __getitem__(self, key: str) -> DataArray: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def assign_coords(self, **coords: Any) -> "Dataset": ...
    def to_netcdf(self, *args: Any, **kwargs: Any) -> Any: ...
    def to_dataframe(self) -> Any: ...
    def interp(self, *args: Any, **kwargs: Any) -> "Dataset": ...


def open_dataset(*args: Any, **kwargs: Any) -> Dataset: ...
def decode_cf(ds: Dataset) -> Dataset: ...
