const fs = require('fs');
const path = require('path');

const agentsDir = path.join(__dirname, '..', 'packages', 'agents');
const outputPath = path.join(__dirname, '..', 'docs', 'agents_manifest.md');

function listAgents(dir) {
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.ts') && !f.endsWith('.test.ts'))
    .map(f => path.basename(f, '.ts'))
    .sort();
}

function generateManifest(agents) {
  const lines = [
    '# Agents Manifest',
    '',
    'This file is auto-generated by `scripts/compile_agents_manifest.js`.',
    '',
    '## Available Agents',
    '',
    ...agents.map(name => `- ${name}`)
  ];
  return lines.join('\n');
}

const agents = listAgents(agentsDir);
const content = generateManifest(agents);
fs.writeFileSync(outputPath, content, 'utf8');
console.log(`Generated ${outputPath} with ${agents.length} agents.`);
