import fs from 'fs';
import path from 'path';

function generateReadmes(packagesDir = path.join(__dirname, '../packages')) {
  const dirs = fs.readdirSync(packagesDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);

  dirs.forEach(dir => {
    const readmePath = path.join(packagesDir, dir, 'README.md');
    if (!fs.existsSync(readmePath)) {
      const content = `# ${dir}\n\nAutogenerated README for \`${dir}\`.\n`;
      fs.writeFileSync(readmePath, content);
      console.log(`Created README for ${dir}`);
    }
  });
}

if (require.main === module) {
  generateReadmes();
}

export { generateReadmes };
