apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyramid-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyramid-ui
  template:
    metadata:
      labels:
        app: pyramid-ui
    spec:
      containers:
        - name: pyramid-ui
          image: pyramid-ui:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: pyramid-ui
spec:
  selector:
    app: pyramid-ui
  ports:
    - port: 80
      targetPort: 3000
