name: "Auto-Backport"
on:
  pull_request:
    types: [closed]
    branches: [main]
jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Cherry-pick
        run: |
          git checkout stable/0.4.x
          git cherry-pick -x ${{ github.event.pull_request.merge_commit_sha }} || true
          git push || true
